### ISSUE TITLE
Make review of submissions transparent

### ISSUE THREAD

**Issue by bmkramer** [force11/force2017#101]
Trying to practice what we preach: can we see whether we can find a way to one or more of the following:

- make submissions publicly visible (ask/tell people on the submission form that this will happen)
- allow commenting on submissions
- make selection criteria transparent and public
- make review decisions public

Of course this is again dependent on the possibilities of the system we are using, but I wanted to put it out as a suggestion anyway. 

Please note this does not imply community-voting (which would be a whole different discussion), but it would allow for a more transparent process, in line with Force11 values :-)

**Comment by Eleonora-Dagiene** [comment]
Regarding 1st and 2nd: I guess it is too innovative and not acceptable for any researcher to make submissions publicly visible. However, authors could decide if they are willing to make their submission publicly visible during a submission process (if the system has such a possibility).
Good news, that it is easy to implement 3rd and 4th – we just declare a policy with selection criteria on the conference website  and follow it in a fair way.

**Comment by kamc** [comment]
I think it is the future of open communication for all of the above to happen and for that to be the norm. But that is my wishful thinking perhaps. But do we know if there is any way for the first two to happen with Copernicus?

**Comment by kamc** [comment]
Per call 7/20/17

Submission form did not ask for permission to share submission openly.

**Comment by bmkramer** [comment]
Yes, that's right - that fell through the cracks :-( 

We did ask if submission is made available somewhere open, but that will be a minority, I'd expect. 

So, 2 options?
a) acknowledge submission and ask if submission and peer review can be made openly available? (would require separate email-workflow by us)
b) As per @Eleonora-Dagiene suggestion above: make at least review criteria transparent

**Comment by bmkramer** [comment]
related to #119 Scoring rubric for submissions review

**Comment by bmkramer** [comment]
I suggest we close this for now (together with #119), but make a note for next year.
