### ISSUE TITLE
Organize a room for the pre-conference fellowship event

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#103]
as per #53.

**Comment by Daniel-Mietchen** [comment]
@mfenner Who have you been in contact with over the OA week event? Could we ask them to give us a room on the day before the conference?

**Comment by kamc** [comment]
From Martin's email (7/6/17):
"in the steering group call today we decided to have an event for travel fellows on Tuesday (the day before the conference starts), and that the program committee work on the program for that event. I am happy to help finding a venue for this, and to participate in the event.

My first choice would be the GFZ Potsdam (http://www.gfz-potsdam.de/en/home/), as it is a nice science campus, I have good connections, it might be easier to get a room than in central Berlin, plus Potsdam is a nice place for touristic activities (e.g. for a joint dinner). Public transportation from central Berlin to Potsdam is easy, but it will take 30-45 min.

Let me know whether I should ask for a venue, or whether you prefer a more central location."

**Comment by kamc** [comment]
From Martin's email (7/6/17):
"in the steering group call today we decided to have an event for travel fellows on Tuesday (the day before the conference starts), and that the program committee work on the program for that event. I am happy to help finding a venue for this, and to participate in the event.

My first choice would be the GFZ Potsdam (http://www.gfz-potsdam.de/en/home/), as it is a nice science campus, I have good connections, it might be easier to get a room than in central Berlin, plus Potsdam is a nice place for touristic activities (e.g. for a joint dinner). Public transportation from central Berlin to Potsdam is easy, but it will take 30-45 min.

Let me know whether I should ask for a venue, or whether you prefer a more central location."

**Comment by EJ-Van** [comment]
I have never lived in Berlin, but I have visited many times and I'm somewhat familiar with the area around the conference venue. Some departments of Humboldt are nearby. There may be a good space that has the same sort of campus feel discussed on the call today. The natural history museum (Naturkundemuseum) and Hamburger Bahnhof (an incredible contemporary art gallery) are also close by and might have something suitable. The Charite hospital campus is also not far and might have a good venue for this sort of event.

**Comment by kamc** [comment]
Those all sound like great ideas Eric! I would LOVE to help with this event, but this part of the process is where I am at the greatest disadvantage because I have never been to Berlin and live nowhere close. So, I am very much enjoying everyone else's thoughts and ideas and they are all just getting me more and more excited for October!

**Comment by kamc** [comment]
From call 7/20/17:

Martin has a location in mind that is a small campus a bit outside of Berlin. Might cause some logistical challenges for getting the fellows sponsors there and the board for the reception.

    Martin will look into some potential venues closer in as well and report back.

**Comment by kamc** [comment]
Any word on this @mfenner ?

**Comment by Daniel-Mietchen** [comment]
This finally took place in the Galerie room, and seems to have worked nicely.
