### ISSUE TITLE
Shall the abstract submission form contain an option to indicate "I need speedy review" or so?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#110]
That might help alleviate some of the timing issues for people to arrange for visa/ travel/ funding.

**Comment by Daniel-Mietchen** [comment]
If so, we need to inform Copernicus by tomorrow.

**Comment by bmkramer** [comment]
One other way around this could be to accommodate at least a poster for any
submission meeting basic criteria (which would require basic review, but no
selection yet).

This might be of use to people for whom permission to travel/participate in
a conference hinges on the condition of presenting.

The problem with speedy review for acceptance within the program lies in
the building of a coherent program (over the 3 days as a whole) - for that
we'd probably need to be able to have an overview of all submissions.

A third way might be to accept submissions based on merit/content without
yet being able to place them in the context of the program as a whole -
depending on the number of expected submissions that might be workable, if
not ideal.

Shall we discuss this further on our call tonight?

regards,
Bianca

**Comment by kamc** [comment]
It also seems like this would cause some amount of preferential selection for those who select that box. That seems somewhat a negative to me as we have no way to know how wonderful the rest of the submissions will be.

**Comment by mfenner** [comment]
Discussion in last program committee call on July 6. Decision to have submission deadline on August 15 (see #111), and to add text "Will you need a visa in order to be able to attend FORCE2017?" to submission form
