### ISSUE TITLE
Define a way to get the schedule on the conference website

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#114]
right now, it's just a gdoc, but at some point, we need it on the website.
We need to define the workflows around that.

**Comment by mfenner** [comment]
I suggest we figure out what help Copernicus can provide, given that we have customized submissions. And look at sched.com otherwise: https://force2016.sched.com/

**Comment by bmkramer** [comment]
Schedule posted on website and Force11 list: https://docs.google.com/spreadsheets/d/1DH8FfDOGOqzYpCjVJK4aZcVq0vk4d-77fx7MUHRLV_Q/edit?ts=59d3ed4c#gid=1382709557

Closing issue.
