### ISSUE TITLE
What do these new labels mean? :)

### ISSUE THREAD

**Issue by LouWoodley** [force11/force2017#121]
Lou and Heather assigned the following tags to all tickets.

3 main types of activities:
A. Content and Logistics
B. Communications and Engagement
C. Social

With timing:
1a. Early planning tasks = up to end of July
1b Mid planning tasks = to do in August
1c Late planning tasks = to do in September
2. Two weeks = to do in early October
3. During conference
4. After conference

If you click on a label, that will filter all of the tickets to show only tickets with that label. So if you want to see all the early planning tasks, click the early planning tasks label :)

**Comment by Daniel-Mietchen** [comment]
I think these more structured labels were useful, and so as this meta ticket to explain them.
