### ISSUE TITLE
Communicate about submissions needing visa 

### ISSUE THREAD

**Issue by bmkramer** [force11/force2017#123]
For submissions that have indicated they need visa, we said we wanted to reach out to them before the abstract submission deadline August 15. We discussed earlier that if the submission is not widely off-base, we would reach out early and tell them we can at least offer them a poster presentation, pending a decision on another format. Then, they can choose to register based on that. AFAIK, further visa requirements are then handled by Copernicus. 

We need to assign responsibility for this:

- do a quick check of the submissions requiring visa, for basic fitness
- send out an email informing them of basic acceptance (poster at least, definitive decision on format to be communicated later)
- refer to Copernicus for visa supporting letter? 

Sample communication letter (please edit as needed):

_Dear ….

Thank you for your submission for Force17. Based on your submission, we are happy to guarantee you participation in Force17 with at least a poster. A decision on the presentation format of your choice is to be made in early September, after the deadline for submissions has passed and all submissions have been reviewed. We hope this guarantee of participation can facilitate your visa application. If you need an official letter to support your visa application, please contact [Copernicus email] and we would be happy to assist you. 

We hope to see you at Force2017 in Berlin!

with regards, on behalf of the Force2017 Programme Committee,
xyz_

**Comment by Daniel-Mietchen** [comment]
Thanks - I've edited it slightly.

**Comment by bmkramer** [comment]
Thanks! Just wondering whether we should mention that they are responsible for their own registration and payment - as to avoid any ambiguity about that...

**Comment by kamc** [comment]
I believe this has been handled now.
