### ISSUE TITLE
Make group photo slot in schedule 

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#125]
perhaps somewhen during a coffee break.

**Comment by kamc** [comment]
When do we do this? Would a coffee break be long enough to have down time, get a drink, and do a photo? Otherwise perhaps it could happen during the social event or maybe during one of the lunch breaks?
#44 
#14 Hindawi social
#32

**Comment by Daniel-Mietchen** [comment]
We had a dedicated slot in the schedule, but there was confusion as to where it would take place, and the [final location](https://twitter.com/jeroenbosman/status/923657705654538241) amidst unrelated cars was not ideal.

**Comment by Daniel-Mietchen** [comment]
Since we have #126 for the photo location, I am closing this ticket.
