### ISSUE TITLE
Make group photo

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#127]
depends on #125 #126.

**Comment by Daniel-Mietchen** [comment]
Photo was done: https://twitter.com/jeroenbosman/status/923657705654538241 .
Haven't yet seen it shared in a reusable manner though.

**Comment by bmkramer** [comment]
Photo was sent to the programme committee, cam be added to materials on
GDrive.

Op dinsdag 31 oktober 2017 heeft Daniel Mietchen <notifications@github.com>
het volgende geschreven:

**Comment by Daniel-Mietchen** [comment]
Why not put it somewhere public, e.g. Flickr/ WikiCommons or some such, and under an open license?

**Comment by bmkramer** [comment]
Sure! :-)

Op dinsdag 31 oktober 2017 heeft Daniel Mietchen <notifications@github.com>
het volgende geschreven:
