### ISSUE TITLE
Shall we have a room where people can take remote meetings?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#128]
Not sure, but wanted to make sure we think about this.

**Comment by bmkramer** [comment]
+1, both for people needing to take meetings and for possible online outreach (e.g. set calls for people following the conference remotely), if we decide to do any of that

**Comment by kamc** [comment]
This could possibly happen in the Atelier room if it is not being used as an unconference space at the time?

**Comment by bmkramer** [comment]
Yes, I like that for this purpose. 

Also relates to #132

**Comment by Daniel-Mietchen** [comment]
I had to take a remote meeting during the event, and finding a quiet space was doable, but the WiFi was more of a problem.
