### ISSUE TITLE
Describe and point out conduct at opening speech

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#130]
ideally with a prominent and human-typable link

**Comment by bmkramer** [comment]
Also relevant:
https://medium.com/@lorraine_chu3n/being-nice-is-not-enough-b9f4f9184707


Op vrijdag 11 augustus 2017 heeft Daniel Mietchen <notifications@github.com>
het volgende geschreven:

**Comment by Daniel-Mietchen** [comment]
I think this worked. A good spin to this was also that we had a brief recap at the end of the event to report on any incidents. Luckily, there was nothing to be reported, but being transparent and forthcoming about having monitored seems useful.
