### ISSUE TITLE
Find a set of tools/ instruments to signal end of breaks/ talks

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#131]
Should be effective but more pleasant than annoying.

**Comment by bmkramer** [comment]
Where to find that gong? :-)

2017-08-24 15:48 GMT+02:00 Daniel Mietchen <notifications@github.com>:

**Comment by bmkramer** [comment]
I'll bring a school bell!

**Comment by Daniel-Mietchen** [comment]
The school bell was great, but having the venue do it via their gong was more effective. Next time, we should probably ask the venue whether they already have a system for that.
