### ISSUE TITLE
Arrange a session for just before the poster session that would include OABB 

### ISSUE THREAD

**Issue by kamc** [force11/force2017#132]
Are we still planning to do this? If so, what are we thinking to do for this? Are there some OA session submissions that could be pulled together for some sort of panel discussion? Should we invite the OABB people to give a short presentation on their local efforts with suggestions for efforts in other places or something? (Just throwing out the first thoughts that came to mind to get the ideas flowing.)

Connected to #42

**Comment by mfenner** [comment]
Yes, that is the plan, and the Berlin OA folks are selecting 10 posters and have started to plan a session. Once we have the submissions sorted out, we can schedule this for Thursday 5-6 PM, followed by posters 6-8 PM.

**Comment by kamc** [comment]
This is now scheduled. What all do we need to know from or inform the OABB people of for this session? How do we get the info about what this session will be to include in the program?
