### ISSUE TITLE
Accessibility of venue

### ISSUE THREAD

**Issue by bmkramer** [force11/force2017#134]
How accessible is the venue, and how can we improve on that? 

Some issues to consider [not complete, please add]

- wheelchair accessible (ramps, elevator, washroom(s)?)
- gender-neutral washroom(s)?
- is there a way we could provide some form of childcare? 
- can we have quiet places for: breastfeeding, prayer, recharge/quiet prep

Also see (and add from) the [Less Obvious Conference Checklist](https://github.com/erikr/lessobviouschecklist#accessibility)

**Comment by kamc** [comment]
Also, having a space to take a remote call was mentioned.

**Comment by bmkramer** [comment]
This issue was moved to force11/force2018#9
