### ISSUE TITLE
Really try to make sure that slides et al. are openly available when talk starts

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#136]
This is a hard one, so I put "try" into the title, but I really mean it. Sharing the slides such that attendees in the room or afar can access them while the talk is going on (and later) is such a useful feature that most conferences lack, and making progress on this would help highlight our theme of changing the culture.

**Comment by kamc** [comment]
I really like this idea. And really I think in part this comes back to the idea of getting everything into Figshare or whatever ahead of time. So far, I don't believe we have even invited people to share their slides or any other materials anywhere at all. When/how should we approach this?

**Comment by Daniel-Mietchen** [comment]
We really, really tried in multiple ways and with multiple reminders, but some slides are still not up.

**Comment by bmkramer** [comment]
This issue was moved to force11/force2018#7
