### ISSUE TITLE
Review open tasks in terms of whether and how they could be given a "changing the culture" spin

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#137]
Here I mean we should be thinking of ways to do each of these tasks that are somewhat different from usual but in a useful, interesting and not too distractive way, just so that (some) people notice and we can then use it to underlign that "changing the culture" is not just a monolithic far-away thing, but involves lots of little things in contexts that people are engaged in on a daily basis.

Some of the things I have in mind here would be if we could manage to actually
- take notes collaboratively (as per #135)
- share their slides such that they are available to everyone when the presentation is given (#136)
but it could also be other things (e.g. see the "bring your own badge" suggestion in #122).

I'm setting up the https://github.com/force11/force2017/labels/changing-the-culture label to keep track of tickets like the above where there is at least a rudimentary idea about how that particular task could be given a spin towards highlighting the conference them.

**Comment by bmkramer** [comment]
I added it to the feedback issue ([#113](https://github.com/force11/force2017/issues/133)), which, while not during the conference, will be a way to make this explicit  as well.
