### ISSUE TITLE
Define elements of social program

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#14]
- conference dinner?
- poster/ demo session?
- meetups?

**Comment by kamc** [comment]
Important to note: From Martin Fenner

"There is unfortunately no budget for offsite dinner. We can arrange food and drinks at Kalkscheune a little later once we have secured enough sponsors."

**Comment by kamc** [comment]
Perhaps with the budget limitations mentioned by Martin and the possibility of inviting the Open Access people from Berlin to a poster session, we could simply turn both the first two nights into a social and poster/demo time with good food and drinks. I don't know if the budget would even handle that, but it might be a great way to create that open interaction time and provide additional time for posters/demos.

**Comment by kamc** [comment]
From steering committee call 7/6/2017:
"further planning of the two evening events (Hindawi is sponsoring an evening event on day 1 and we have a joint poster session with Berlin OA Week on day 2), video recording, etc. (15 min)"

**Comment by kamc** [comment]
Not really need to do anything here, except for other extending items.

Do need to give Hindawi about 2 minutes or whatever at the end of Christopher's plenary session.
