### ISSUE TITLE
Assign people as session chairs

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#142]
and give them instructions (cf.  #141).

**Comment by kamc** [comment]
There is now a copy of the program in which people can go in and sign themselves up to be a room chair. We did discuss if we are planning to include the travel fellows in that work, but I am unclear what was decided about that or how we would invite them to sign up. When would we like to invite people to go in and sign themselves up? And how much would we like each person to volunteer for or limit themselves to?

**Comment by kamc** [comment]
I believe this is the right link for the spreadsheet to sign up on.
https://docs.google.com/spreadsheets/d/12KegT8b4B8gKci-8GOMFSK6aK8P0vyLuvVybdFfhhpA/edit?usp=sharing

**Comment by bmkramer** [comment]
For the travel fellows, I think we discussed perhaps involving them as notetakers. 

For session chairs, we can also suggest specific names other than the programme committee as chairs where we feel that would fit particularly well.

**Comment by Daniel-Mietchen** [comment]
This worked. Not aware of any problems.
