### ISSUE TITLE
Think through format of town halls and daily reflections/report outs

### ISSUE THREAD

**Issue by LouWoodley** [force11/force2017#144]
Who's going to lead these conversations? Can we summarise according to the theme of the day e.g. "Today's theme was what's happened to date in scholarly comms, three key takeaways from the day are..."

**Comment by bmkramer** [comment]
Also consider other things to address in town halls - e.g. open comments/reflections from floor. 

Fort he closing town hall (day 3), I liked how in both Oxford and especially at Portland, the recap was really a discussion with the audience on how to move forward, seeded by closing remarks.
