### ISSUE TITLE
Plan the fellow lightning talks

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#15]
i.e. lightning talks by the Force 2017 fellows.
currently, they are penciled in for two sessions - one directly after keynote 1 (#10), the other after keynote 2 (#11)

**Comment by kamc** [comment]
Who contacts the fellows about doing the lightning talks? I assume the program committee, but don't know. To my knowledge this has not been done yet, but needs to be. The same is true for fellows doing a poster or a demo. Those that volunteered to do a blog can likely simply be reminded at the event, but a note of thanks for their willingness to blog about it might be a good thing as well.
