### ISSUE TITLE
Overview of open issues

### ISSUE THREAD

**Issue by bmkramer** [force11/force2017#151]
Last updated 20170928

_GENERAL_
#50 Aim for diversity and inclusivity
#137 Review open tasks in terms of whether and how they could be given a "changing the culture" spin

SOCIAL PROGRAMME / SATELLITES / FELLOWS_  
_- Social_
#14 Define elements of social program - **assign**
_- Satellites_
~~#69 Make a list of events/ communities that might be (or become) a basis for satellite events~~ - **CLOSED**
~~#45 Coordinate with satellite events - **Outreach committee?**~~ **CLOSED**
_- Fellows_ 
#53  Pre-conference event for fellows - **assign** @mfenner any new info on this that we should be aware as well as sending information to all fellows?
#103 Organize a room for the pre-conference fellowship event - **assign** same as #53 @mfenner any new info on this that we should be aware as well as sending information to all fellows?
~~#129 For people who get a scholarship but have their visa denied, earmark them for a 2018 fellowship?~~ **assign** **CLOSED**
~~#71 Are we doing a Digital Library Federation cross-pollinator travel award?~~ **suggest for 2018? CLOSED**

LOGISTICS
_- General_
#134 Accessibility of venue **Programme committee** -> **Copernicus**
_- Schedule overview_
#35 Reduce confusion in terms of what happens when and where 
~~#48 Help attendees organize themselves **decide on Sched**~~ **CLOSED**
~~#114 Define a way to get the schedule on the conference site - **Programme committee** -> **Copernicus**~~ CLOSED
#150 Add floor plans of the venue to Force 2017 website - **Copernicus**
#149 Prepare signage for onsite - **Copernicus**

_- Make materials available online_
#59 Create Figshare collection for all posters and slide decks? **Programme committee** cf **Copernicus** @Daniel-Mietchen @mfenner please let us know if we will be instructing presenters to post their presentations and other materials on figshare or Copernicus site?
#75 Ensure that presentations are available online by default when they are given same as #59 
#136 Really try to make sure that slides et al. are openly available when talk starts

_-Venue logistics_ #59 
#145 Set a useful password for the event WiFi – **Copernicus**
#147 Include WiFi password in conference printouts - **Copernicus** **assign to Copernicus**
#128 Shall we have a room where people can take remote meetings? - **Copernicus** (see also #134 Accessibility) ** @bmkramer  prepare a list of questions for Copernicus**
#83 Venue seating for networking - **Copernicus** 
#82 Test all technology tech support website - **Copernicus**

_- Session facilitation: chairs, note taking, signalling breaks_ **Programme committee?** **send a message to all PPC and SC to sing up to chair a session**
#143 Plan communications between session facilitators
#142 Assign people as session chairs **action for Programme committee**
#141 Write instructions for session chairs 
#135 Think of a consistent system for taking notes during each session **make decision on this**
#139 Write instructions for collaborative note-taking
#138 Assign people to coordinate note taking for each session
#131 Find a set of tools/ instruments to signal end of breaks/ talks
#140 Assign people to signal the end of breaks 
#146 Identify & instruct mike runners **ask Copernicus about number of mikes** 

_- Remote participation_ **ask Stephanie about streaming  -to which channel**
#49 Plan for remote participation 
#148 Consider using something like GoToMeeting for every session **for 2018?**
#58 Set up a Force11 YouTube channel **see above re: streaming**
#56 Make a plan for the twitter wall - **Outreach committee?**
#87 Prepare a Twitter archive - **Outreach committee?**

_- Miscellaneous_
~~#76 Arrange graphic notetakers - **Programme committee** **decide  10/5/17**~~CLOSED
#116 Set up a voting mechanism for the idea pitch **decide 10/5/17** PENDING 
~~#122 Shall we go for a "Bring your own badge" system?~~ **CLOSED**
#124 Explore Open Housing **ideas for 2018**
#133 Create an option for people to indicate why they can't or won't attend the conference - **for evaluation** **after the conference**

_-Group photo_  **assign** **Copernicus to suggest a place**
#127 Make group photo
#126 Select space for group photo **ask Copernicus for suggestion**
#125 Make group photo slot in schedule **Before Poster Session** or after **Christopher talk**

SCHEDULE - **Programme committee**
#115 Thinking about welcome/intro talk @mfenner to do the intro talk
#130 Describe and point out code of conduct at opening speech @mfenner 
~~#100 Consider ways to link the keynotes~~ **CLOSED**
#44 Plan breaks **fit into schedule over coming week**
~~#32 Plan lunch talks/ demos~~ **CLOSED**
#15 Plan the fellow lightning talks @kamc **will email the ones that indicated are willing to do a verbal presentation about date, time and duration**
~~#132 Arrange a session for just before the poster session that would include OABB~~ **CLOSED**
#42 Plan poster session
#43 Plan demo session
#46 Plan late breaking talks 
#22 Plan the main unconference **decide on call Oct 5**
#144 Think through format of town halls and daily reflections/report outs
#16 Pitches for idea challenge
#17 Announcement of idea challenge winners 
#52 Provide slot for last year's idea challenge winners to speak? **slot is scheduled, yes/no decision required**
~~#84 Consider doing a doathon~~ **CLOSED**

WEBSITE – **Outreach committee** / **Copernicus** **ALL DONE?** 
#106 Add link to "home" for main logo / graphic in banner of conference site
#105 Add tagline to website
#98 add Nicky as the contact person for the Force2017 website outreach
#97 create flyer for outreach
#96 create a list of bullet points about Force2017 that can be used for publicity via various means
#95 post Force2017 conference on various calendars?
#94 Add publicity materials to website
#93 Add a key dates section on the home page
#90 Info about sponsorship opportunities on homepage needs revision
#89 two websites for Force2017 - combine into one?
#86 add a FAQ page to the website
#74 Create SVG versions of FORCE2017 logo 
#70 Make logo prominently available from website
#64 need description of Force2017

HOW TO INVOLVE – **merge into 1?**  
#65 Think about how to involve publishers
#34 Think about how to involve makers/ hackers/ DIY folks
#33 Think about how to involve artists
#31 Think about how to involve media
#30 Think about how to involve the public
#29 Think about how to involve funders
#28 Think about how to involve students
#27 Think about how to involve developers
#26 Think about how to involve librarians
#25 Think about how to involve research administrators
#24 Think about how to involve researchers

PROCEDURE - **leave as is**
#81 Ensure more active engagement of those that volunteer
#63 Assign responsibilities for all open issues with a "program" label
#54 Define mechanism for assigning responsibilities

CLOSE - **review**
~~#80 Publicity plan - what is the program committee's role with publicity?~~ **CLOSED**
~~#79 Track sponsors - what is the program committee's role with sponsorship?~~ **CLOSED**
#23 Plan the idea pitch unconference – **CLOSE?**
~~#62 Assign milestones to all issues with a program label~~ CLOSED
~~#6 Define milestones for program committee~~ CLOSED
~~#40 Plan wrap-up for day 3~~ – CLOSED – replace by #144
~~#39 Plan wrap-up for day 2~~ – CLOSED – replace by #144
~~#38 Plan wrap-up for day 1~~ – CLOSED – replace by #144
~~#37 Plan daily wrap-ups~~  CLOSED – replaced by #144
~~#21 Define scope of town hall meeting 3~~– CLOSED - replaced by #144
~~#20 Define scope of town hall meeting 2~~ – CLOSED - replaced by #144
~~#19 Define scope of town hall meeting 1~~ – CLOSED - replaced by #144

**Comment by Daniel-Mietchen** [comment]
I just closed #6 and #62 and updated the list above accordingly.

**Comment by kamc** [comment]
We may want to discuss how we share the code of conduct with presenters at least and possibly with attendees as well.
#91
