### ISSUE TITLE
Define channel for planning the unconference

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#155]
e.g. a dedicated page with the emerging schedule, perhaps even displayed on a monitor near the break area.

Ties in with #22.

**Comment by gmhagedorn** [comment]
Create a push-communication to activate visitors to motivate them to participate in specific sessions, to be informed, beyond a general announcement that they may check a github page - something easily forgotten in information overflow during the conference

**Comment by Daniel-Mietchen** [comment]
This worked fine by way of a [Google spreadsheet](https://docs.google.com/spreadsheets/d/1wEYzmZ2RNo3vFO-URxMOa5Om0NW157LJQj2dU2Z2U5Y/edit#gid=0).
