### ISSUE TITLE
Collect event coverage

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#156]
We need to bring together in a useful fashion
- the collaborative notes (#135)
- presentations (#75)
- demos (#43)
- posters (#42)
- video recordings (apparently no ticket for that?)
- Twitter (#87)
as well as 
- blog posts (e.g. http://gigasciencejournal.com/blog/force2017-in-berlin-changing-the-culture/ or http://openminted.eu/openminted-participates-force2017-conference-two-highly-attended-workshops/ )
- pictures people have taken at the event (e.g. #127)
- any other materials (images, audio, video, text, annotations, 3D, whatever)

**Comment by Daniel-Mietchen** [comment]
Another one: https://www.force11.org/blog/new-ideas-discussed-force2017

**Comment by Daniel-Mietchen** [comment]
For inspiration on how to present the information, see the FORCE2016 Final Report.docx, which sits in the Final Reports folder in our Gdocs.

**Comment by bmkramer** [comment]
This in on our action list of things to complete for FORCE2017 - leave issue open for now
