### ISSUE TITLE
Pitches for idea challenge

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#16]
Currently penciled in for after round two of the fellow lightning talks (#15), on day 2.

**Comment by kamc** [comment]
From Robert on the agenda July 13, 2017:

Jisc sponsorship of Pitch-It Challenge - they have asked whether we can focus the challenge on responsible metrics/open metrics?
Perhaps make relevance to that topic a judging criterion?


Need someone that can keep run this event.

Also discussed using something similar to what was used last year for the polling app we used last year.

**Comment by kamc** [comment]
#

**Comment by kamc** [comment]
Sorry - I was trying to connect this to the new ticket about this. It's ticket #117

**Comment by kamc** [comment]
We need to know for certain if there will be an idea challenge or not. For right now we have not scheduled any time for it, but if it is still happening, perhaps it could happen during one of the lunch breaks #32 or something?
