### ISSUE TITLE
Define number of town hall meetings

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#18]
we currently have three:
- one after keynote 1 and fellow lightning talks (#10 and #15)
- one in the morning of day 2, before keynote 2 (#11)
- one in the closing session, after announcement of the idea challenge winners (#17)

**Comment by LouWoodley** [comment]
Is this done?

**Comment by kamc** [comment]
We have a little time for this before the day 2 keynote - to recap day 1 I assume. We have 30 minutes scheduled for day 2 in the afternoon. And there is an hour scheduled for "town hall and closing" in the afternoon of day 3.
