### ISSUE TITLE
Plan the main unconference

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#22]
The current plan is to have one room open for an unconference throughout the event.

We don't have to plan the program for that, but should still think about which room to choose for this, and how to equip it.

I am using the term "main" unconference here because there has also been a suggestion to have an unconference style session or track devoted to working on the ideas from the idea challenge.

**Comment by bmkramer** [comment]
+1 for linking with #48 

At the very least, it should be clear to all participants what is happening at the unconference sessions, so they can decide whether they want to join in at any given time. This would require people organizing an unconference session to self-report in the system. 

A more involved planning system would involve a dedicated planning activity (can be online) where people propose sessions/topics and schedule time slots. In a simple form, this can be done by  allowing people to fill out pre-defined time slots (not unlike the self-reporting above, but encourage people to do this in advance). A more involved planning activity would involve other participants expressing potential interest and allot time slots based on that.
