### ISSUE TITLE
Think about how to involve makers/ hackers/ DIY folks

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#34]
Perhaps as part of the main program (e.g. the lunch breaks, as per #32), through satellite events or dedicated outreach.

**Comment by nicolevasilevsky** [comment]
We have a list of listservs to email, please add any additional email addresses you'd like us to contact here: https://docs.google.com/spreadsheets/d/1ipgcSuevwiPufvCwfeMziGxtpxl0x2zREODMX8hEjmE/edit#gid=0

My colleague put on a Science Hack Day in Portland, I'll ask if she has any email lists we can target.
