### ISSUE TITLE
Add theme to Force 2017 website

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#36]
as per
https://github.com/force11/force2017/issues/9#issuecomment-299326160 .

**Comment by kamc** [comment]
Might want to include a logo if we are going to create one.
Issue #66

**Comment by Daniel-Mietchen** [comment]
Just checked - couldn't find it on
http://www.force2017.org/
or https://www.force11.org/meetings/force2017 , so 
pinging @sthagstrom again.

**Comment by TAC-NISO** [comment]
Noting that this still hasn't been added to the site. @sthagstrom

**Comment by kamc** [comment]
It is located as part of the logo on https://www.force2017.org/ but is still not on https://www.force11.org/meetings/force2017 that I can see at least. Also, do we need it more prominently expressed on the first site than simply in the logo?

**Comment by kamc** [comment]
I forwarded the above comment on to Stephanie via email. :)

**Comment by kamc** [comment]
I heard back from Stephanie and she said that the second of the links is unpublished and traffic is being directed to the site at Copernicus instead. So, if we would like the theme more prominently stated someway on the first link, we need to forward that information to Stephen Diggs who will be acting as the connection point to Copernicus about the website.
