### ISSUE TITLE
Plan poster session

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#42]
should be coordinated with 
- demos (#43)
- lunch talks/ demos (#32)
- social events (#14)
- submission (#2)

**Comment by kamc** [comment]
Per Martin's email on May 10, including the Berlin OA folks for at least a poster session sounds like a good way to reach out. Also, with what Mellissa discussed about attempting to offer everyone who wishes to present a slot to at least do a poster or demo, having two nights of poster/demo time would be a good option. One could be specifically focused on Open Access issues (obviously that would be when to involve the Berlin OA posters) and the other be focused on everything else and any overflow of OA items.

**Comment by kamc** [comment]
One caution based on experience from both last year and the year before: We need to carefully arrange functional open space for the posters. Last year, there were areas that were virtually trapped by the arrangement of the boards which cased some challenges in attempting to communicate with people in the corners of the cubicles created by the placement of the boards. The year before, there seemed to be some stranger angles to things, but it kept it a bit more open. It is something we just need to be aware of. We need open access to the posters and presenters of them as well as to scholarly literature. ;)

**Comment by kamc** [comment]
Important to create a good balance between social and poster interactions.

**Comment by kamc** [comment]
Further info - Berlin OA poster info from Martin’s email (7/6/17):

- Berlin OA group (OABB) would like to have a session focused on OA activities in Berlin/Brandenburg before the poster session (Thursday, Oct. 26, at 5pm-6 pm) - OABB would organize session

- Then poster session from 6-8. Posters from both conference attendees and OABB. Force11 would take care of catering event and OABB would handle registration and nametags for their folks (expect about 50-70 people)

**Comment by kamc** [comment]
Looking for additional sponsors to pay for that.

**Comment by bmkramer** [comment]
Do we have a list of current sponsors somewhere? (before spouting suggestions :-)

**Comment by kamc** [comment]
Need still to decide if/how to arrange a session for just before the poster session that would include OABB folks.

**Comment by mfenner** [comment]
List of current "official" sponsors is at https://www.force11.org/meetings/force2017/sponsorship/opportunities. Spreadsheet with work in progress in Force2017 folder.

**Comment by bmkramer** [comment]
Thanks!

**Comment by kamc** [comment]
We have room for about 40 posters comfortably. (per call 8/24/17)

**Comment by kamc** [comment]
Does Copernicus provide the pins or whatever for everyone to hang their posters with and the signage for each poster I assume?

**Comment by kamc** [comment]
Need to go back through the submissions and see which ones we wanted to also add a poster for and get them added in. Same with the demos. #43
