### ISSUE TITLE
Plan late breaking talks

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#46]
It often happens that interesting topics pop up after a conference has had a submission deadline or even defined the overall program.

We plan to address this by having a session for "Late breaking talks", currently set to 12:00-13:30 on Friday as a plenary.

**Comment by nicolevasilevsky** [comment]
+1 great idea

**Comment by Daniel-Mietchen** [comment]
Here are the ideas so far:
- someone from the RDA Berlin team on interactions between RDA and Force11
- someone from http://data4sdgs.org/ on linking research with the Sustainable Development Goals and their indicators

**Comment by kamc** [comment]
Also added was Martin's submission about the citations WG
