### ISSUE TITLE
Plan for remote participation

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#49]
- evaluate potential channels for remote participation
  - e.g. 
    - live stream (video and/ or audio)
    - presentations online before talk starts
    - Twitter hashtag(s)
    - GitHub tickets
    - collaborative note-taking

- review existing tickets as to whether remote and on-site participants should be treated differently (e.g. we don't need food preferences for remote attendees)

**Comment by kamc** [comment]
If we have individuals assisting in sessions, questions/comments could be invited via Twitter (or whatever other means) and shared by that facilitator like any other question.

**Comment by Daniel-Mietchen** [comment]
I'd like to remain open to more active remote participation too, e.g. some talks could be given remotely.

**Comment by nicolevasilevsky** [comment]
+1 to questions or comments via Twitter

**Comment by kamc** [comment]
Discussion from Steering Committee call 7/19/17 and comments during Program Committee call 7/201/17:

ACTION: Find out how many people actually were on the live streaming to decide if it is a good return on investment and look into the difference in cost between streaming all events in one room vs only the keynotes or plenary sessions.

- Q (BK) How about live-streaming vs. recording? I.e. if we don’t livestream, would we still record and put recordings up on website or figshare? 

- Doing audio in the breakout session rooms seems like enough but without losing the knowledge shared. (KC)

- Remark [BK] Return-on-investment is also dependent on a) how people who used livestream appreciated it (can we evaluate that?) and b) how much outreach is done around livestream, esp. when we focus on inclusivity.

**Comment by bmkramer** [comment]
This issue was moved to force11/force2018#12
