### ISSUE TITLE
Provide slot for last year's idea challenge winners to speak?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#52]
Perhaps right before the idea pitches (#16)?

Not sure they'll attend, so prepare for a remote/ pre-recorded talk if necessary.

**Comment by rhmcdonald** [comment]
I have confirmation that at least 1 person is planning to attend from each winning group last year so I think they will have something.

**Comment by kamc** [comment]
Right before this year's lightning pitches sounds brilliant! However we currently have that slotted for the second half of the fellows doing lightning talks. Should we move those to possibly use a portion of what is currently town hall time that second morning? So Thursday would look something like this:
Town Hall 9:00-10:30
Fellow Lightning Talks 2 10:30-11:00
Coffee Break 11:00-12:00
Keynote 2 12:00-12:30
Last Year's Challenge Winners Lightning Talks 12:30-13:00
Idea Pitches 13:00-13:30
Lunch 13:30-15:00
