### ISSUE TITLE
Pre-conference event for fellows

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#53]
Comment from Melissa in schedule doc:

> Please schedule a half/whole day for fellowship awardees to get special training/interaction with PC/exec. This was a great way to introduce them to community and create new advocates.

**Comment by kamc** [comment]
That is beautiful!

**Comment by kamc** [comment]
Will we have venue space there for this to happen there that day before?

**Comment by kamc** [comment]
From call 7/20/17:

Martin has a location in mind that is a small campus a bit outside of Berlin. Might cause some logistical challenges for getting the fellows sponsors there and the board for the reception. 

- Martin will look into some potential venues closer in as well and report back.

**Comment by kamc** [comment]
What is that we will be doing at this event? I would love to have it be an incredible opportunity for building people and connections and I am happy to help with this in any way.
A few considerations:

- Timing for being with the board and sponsors
- How do we contact/invite board and sponsors
- What do we do in terms of what the workshop time for them includes? What do we offer and who does it?
- Will this be combined with another event? If so, will there be time for the fellows to just gather together as well?

Many others, those are just what was already on my mind.
