### ISSUE TITLE
Define mechanism for assigning responsibilities

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#54]
Every open issue should ideally have at least one assignee, and perhaps a good way to distribute the responsibilities would be to choose labels or combinations thereof as the basis.

Initially, this will only be for program-related stuff, but it can be expanded to other things as needed.

See [here](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) for some background on how assignments work on GitHub.

**Comment by LouWoodley** [comment]
We're creating three broad tags for all the tickets - A. Content and Logistics B. Communications and Engagement and C. Social. Members of the committee can then filter by things they're most interested in and start assigning themselves to tickets.

We've also added tags for early activities, activities within 2 weeks of the confernce, during conference and post-conference.
