### ISSUE TITLE
Make a plan for the twitter wall

### ISSUE THREAD

**Issue by mellybelly** [force11/force2017#56]
A tradition started at BTPDF2 was a twitter wall. 

This requires a few things:
projector that is not conflicting with the main goings on of presentations etc.
someone to monitor for spam/malicious stuff
someone to actively tweet and promote conference activities

**Comment by pgroth** [comment]
We need to look at the venue. Maybe multiple monitors around the venue may be necessary. I don't know if we need to do the monitoring and promotion - this happens spontaneously
