### ISSUE TITLE
Prepare abstract submissions - encourage interactive session formats

### ISSUE THREAD

**Issue by bmkramer** [force11/force2017#57]
Goal: 

- encourage lively, interactive sessions as opposed to just presentations
- successfully convey this when soliciting abstract submissions

**Comment by bmkramer** [comment]
Remarks from email @mfennner:

I would like to propose that we follow a best practice from unconferences: 

1. every session has at least two presenters/facilitators
2. every session has no more than 50% of the time presentation by the session facilitators

If the program committee thinks that this is a good approach, then I suggest that we increase the length of each session from 30 min to 45 min or 60 min. I have used the format with multiple presenters and lots of discussion with both 45 min and 60 min sessions successfully.

**Comment by bmkramer** [comment]
In general  I think we might be able to do even more to encourage interactive formats/discussion in sessions :-) 

'Maximal 50% presentation time' and 'format with multiple presenters and lots of discussion time' does move away from straight-up talks only, which is great. However, it does still evoke the format of talk-with-subsequent discussion only.

I think we can encourage more creativity by mentioning this as one possibility, but also explicitly mentioning and soliciting other format styles for sessions, *and* stating these will be given preference. 

For instance:
- workshop (as general format, lots of what I mention below falls under that of course)
- World Café
- debate
- scenario building (as a group activity)
- landscape mapping  (as a group activity)
- compliance checking of tools, platforms, practices  (as a group activity)
- workflow building  (as a group activity)
- inventorizing/prioritizing x, y or z  (as a group activity)
- soapbox
- stakeholder role play exercise
- simulation
- etc etc

Many of these can of course also be accompanied by a short introduction to provide context, where needed. I'd also suggest that, given really interactive formats, it should be possible to combine two time slots to give paticipants enough time to do actual work, but that can be decided when wrangling submissions into a schedule :-)

**Comment by bmkramer** [comment]
Other comments from email on ' 50%'  proposal @mfenner:

@mellybelly:
=> 50% would be a lot more in the past, where the facilitators did nothing, had a short intro, or gave a talk (which would have been selected as per usual mechanism). I agree though, chairing a session shouldn't entitle one to a bunch of stage time.

We also had only new session chairs (e.g. had not chaired a session at earlier conferences) last year to bring new perspectives to the program. So for example, I would be ineligible to chair a session. Maybe this is too hard to keep going from year to year, but it does assist with freshness :-).

**Comment by bmkramer** [comment]
@Daniel-Mietchen Can you add the appropriate labels to this issue (or grant me rights to do that?) ;-) 
Thanks!

**Comment by Daniel-Mietchen** [comment]
@bmkramer Done (both).

**Comment by bmkramer** [comment]
Thanks!

**Comment by kamc** [comment]
One question about session types: Do we have the ability to accept/suggest/offer flipped sessions, ones where the bulk of the information is disseminated prior to the conference and then more interactive involvement and discussion fills the actual in session time?

**Comment by bmkramer** [comment]
I think we could certainly add that as a possible suggestion!

**Comment by bmkramer** [comment]
Action items from May 11 call (#41)

- Requirements for submission system:
  - checkboxes: session/demos/poster
  - for sessions:
    - given info: 
      - list of format suggestions (as inspiration)
      - possible room setup(s)
    - ask: 
      - min/max time (e.g. one or two 30-minute sessions or flash talks)
      - describe format (free text)
      - subthemes/topics (checkboxes from #9 (can pick more than one) + ‘ other’ option (with free text)
- re-use other fields from last years’ submission forms
- Martin @mfenner and Bianca @bmkramer will make proposal to discuss during next call

**Comment by bmkramer** [comment]
Links to previous years' submission forms:

2016 Call for sessions/posters/demo's
 [https://www.force11.org/eform/submit/session-poster-demo-submission](https://www.force11.org/eform/submit/session-poster-demo-submission) (prior to session submission deadline)
[http://www.force11.org/meetings/force2016/forms/program-submissions](http://www.force11.org/meetings/force2016/forms/program-submissions)
(after session submission deadline)

2016 [PRECONFERENCE WORKSHOP CALL FOR ABSTRACTS ](https://goo.gl/oLkjeN)
2015 [Poster and Demo Call for Abstracts](https://goo.gl/zxNQqW)

**Comment by bmkramer** [comment]
Here are my suggestions for fields to include in the submission form, based on last year's template. 
It helped me to work visually, but it didn't result in an editable template proposal, apologies.... 
But comments and text suggestions will go a long way, I think. 

[https://docs.google.com/document/d/1ApmdZX7wColYij7yaf9W7YAuVsSloEvRTl3sgDlizgw/edit](https://docs.google.com/document/d/1ApmdZX7wColYij7yaf9W7YAuVsSloEvRTl3sgDlizgw/edit
)
Attached see the proposed adapted section for the session formats (part of the document).

Edited: Martin's @mfenner response below:
This looks good to me. We need to align with what Copernicus is offering, e.g. You need to create an account with them, which then can be linked to your ORCID. But I think these will be minor adjustments.

**Comment by Daniel-Mietchen** [comment]
I think this is basically done now, but don't know what the current state at the Copernicus end is. Added the "high priority" label to put it on the agenda for the next meeting.

In any case, this needs to be coordinated with #68.

**Comment by bmkramer** [comment]
Submission form is now ready for distribution. 

Link to admin view (including responses)
https://docs.google.com/forms/d/1yHOZAVVLaPwzFneDc-DGSO25zssKOnrKpoXkMAzzSxM

Link to viewable form for distribution: 
https://docs.google.com/forms/d/e/1FAIpQLSfYPGFaIzZ6I_TaOGjcr45IUuga2rHvLPXUc6cYbUyywqwhHg/viewform

Short url to viewable form:
https://tinyurl.com/force2017-proposals
and with preview:
http://preview.tinyurl.com/force2017-proposals

I asked Stephanie to coordinate this with Copernicus for inclusion on the website. Once that is done, further dissemination can start.


related to #88

**Comment by mfenner** [comment]
Completed.
