### ISSUE TITLE
Set up a Force11 YouTube channel

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#58]
This could help engage with the community between events, and facilitate remote participation during events.

**Comment by sthagstrom** [comment]
We have a You Tube Channel we just never use it and noone manages it (-:  I think it was set up after BTPDF2, because I see those videos here.  We should probably add other conference videos here too.

https://www.youtube.com/channel/UCeoSUmlntunLJU29ODPzx6g/feed

**Comment by natesjacobs** [comment]
I would love to setup a podcast to build momentum going into the conference.  Anyone interested in doing this with me?

**Comment by kamc** [comment]
I've never done that before, but this is a very interesting idea to me and I would be happy to help if you can use a novice. ;)
