### ISSUE TITLE
Create Figshare collection for all posters and slide decks?

### ISSUE THREAD

**Issue by bmkramer** [force11/force2017#59]
This was done for Force2016 by just having everyone add the [tag Force2016](https://figshare.com/search?q=:tag:%20FORCE2016).

**Comment by kamc** [comment]
Need to decide if we will use Figshare again. How well has that collection been used since then?

**Comment by mellybelly** [comment]
Not sure about use, but in prior years we didn't really have a public collection other than the videos on the site. At least this way all content was collected with a DOI, and we were able to experiment with attribution. I think that trying to improve upon last year but still using Figshare would be a good idea.

We need to eat our own dogfood...

**Comment by bmkramer** [comment]
Also, creating a collection is probably going to be a lot easier than last time, when the collection function was not part of Figshare yet.

**Comment by kamc** [comment]
I also enjoyed reading the comments in the lessons learned doc from last year about this.
"What worked well:
It is very nice to have the slides/posters archived and aggregated in the FigShare collection
 
Issues:
Not everyone submitted to FigShare, despite many reminders
Issues with pulling out the data just prior to the conference, as mentioned above
Not everyone used the proper tag"

Those seem like fairly minor issues compared to having it all curated together like that, but that just my thought.

**Comment by Daniel-Mietchen** [comment]
I think having such a collection is good, and Figshare is a reasonable default, but we should think about ways in which stuff hosted elsewhere (e.g. on Zenodo, mybinder) could be made part of such a collection.

Another issue is the timing of the sharing - I just opened #75 for that.

**Comment by mfenner** [comment]
As a first step I suggest to talk to the conference organizer. Also, talk to Force11 as an organization whether there are plans for a generic collection (e.g. the conferences, FSCI, etc.) I can do both and report back.

**Comment by bmkramer** [comment]
Thanks Martin, that would be good.

**Comment by mfenner** [comment]
Copernicus is not hosting any slides or posters, as we opted out of the standard workflow. We are reaching out to Figshare.

**Comment by bmkramer** [comment]
a) I think Figshare is a better option anyway, because of DOIs assigned. 

b) do you want me to take a role in this? E.g. explore the possibilities of a regular collection vs. teh automatic 'pulling' of material based on tag that was done for Force2016?  

c) a remaining issue is how to aggregate Force2017-related material that is stored elsewhere, e.g. code.

**Comment by bmkramer** [comment]
d) related to approaching sponsor for poster session (as per call)?

**Comment by mfenner** [comment]
At this stage John Chodacki is coordinating this. I can also help out with this (given that I work for DataCite).
