### ISSUE TITLE
need description of Force2017 for outreach, sponsorship, etc.

### ISSUE THREAD

**Issue by nicolevasilevsky** [force11/force2017#64]
I created this draft description of the Force2017 conference, it needs edits from the program committee:

https://docs.google.com/document/d/1IcsCM7R-4_puS6G-5YLY_GP6Hj_aZuc_tAkITZn7_Xk/edit

**Comment by Daniel-Mietchen** [comment]
We've given it a first go today and left edits and comments. Need more guidance as to the intended use of the document in order to contribute more productively.

**Comment by LouWoodley** [comment]
Is this done?
