### ISSUE TITLE
Think about how to involve publishers

### ISSUE THREAD

**Issue by heatherstaines** [force11/force2017#65]
How to involve publishers as attendees, presenters, sponsors, etc.

**Comment by heatherstaines** [comment]
Please let me know where I can find the sponsor list from last year, so I can tell which publishers were involved. It would also be good to see from which publishers attendees and presenters came. Where can I see that information?

**Comment by Daniel-Mietchen** [comment]
Pinging @sthagstrom

**Comment by nicolevasilevsky** [comment]
(edited, I added the wrong link initially)

@heatherstaines - here is the list of sponsors from last year, can you request access and I will share it with you: https://docs.google.com/spreadsheets/d/1_MHp6ol2f2y4RLNQ7dVW-ZCaxiK5CcDT5DSOwpsj0uA/edit#gid=2079784969
