### ISSUE TITLE
Create a logo for the conference

### ISSUE THREAD

**Issue by kamc** [force11/force2017#66]
Should connect with #9

**Comment by vioil** [comment]
@sthagstrom is this the official logo? 

http://www.force2017.org/home.html

**Comment by Daniel-Mietchen** [comment]
Different version is at https://www.force11.org/meetings/force2017 .

**Comment by sthagstrom** [comment]
The FORCE2017 logo’s are uploaded to the FORCE2017 folder > LOGOS
https://goo.gl/7g4QoC

Thanks - Stephanie

**Comment by Daniel-Mietchen** [comment]
OK, closing this one, which leaves #70 and #74 open on logo matters.

**Comment by Daniel-Mietchen** [comment]
Update: we have additional logos now that are aware of the conference theme - they are in the FORCE2017 folder > LOGOS https://goo.gl/7g4QoC .
