### ISSUE TITLE
Agenda items for program committee meeting on June 8, 2017

### ISSUE THREAD

**Issue by kamc** [force11/force2017#67]

**Comment by Daniel-Mietchen** [comment]
Should probably largely build on the high-priority issues:
- https://github.com/force11/force2017/issues?q=is%3Aissue+is%3Aopen+label%3Ahigh-priority .

**Comment by kamc** [comment]
Some tickets to include:
#68 Call for Proposals
#70 and #74 Logo
#9 Define themes
#59 Create Figshare collection for all posters and slide decks?
#8 Define number of keynotes, choose keynotes

**Comment by kamc** [comment]
Bianca suggested #24 Think about how to involve researchers

**Comment by Daniel-Mietchen** [comment]
Closing - meeting has ended.
