### ISSUE TITLE
Make a list of events/ communities that might be (or become) a basis for satellite events

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#69]
e.g. MozFest, OA Week etc.

Much of it already in the main doc for the program committee

**Comment by heatherstaines** [comment]
Hypothesis would like to do an event the day before the main conference--we had apparently done a pre-conference last year. We would love to coordinate with the main meeting.

**Comment by Daniel-Mietchen** [comment]
Some related events that take place nearby in both space and time: https://github.com/Daniel-Mietchen/events/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20milestone%3A2017-10%20label%3AEurope

**Comment by mfenner** [comment]
Placeholder page has been added to conference website. http://www.force2017.org/information/other_events.html. Collect info on relevant events here and by the outreach committee, and aim for adding this info to the conference website in early August.

**Comment by mfenner** [comment]
Outreach committee will work on this, plan is to launch page in early August.
