### ISSUE TITLE
Create SVG versions of FORCE2017 logo

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#74]
The FORCE2017 logos are in the FORCE2017 folder under LOGOS https://goo.gl/7g4QoC (cf. https://github.com/force11/force2017/issues/66#issuecomment-306300687 ) but don't currently have SVG versions.

**Comment by kamc** [comment]
Do you want them all in SVG? If not, which one(s)?

**Comment by Daniel-Mietchen** [comment]
All of them, as we don't know which ones are more likely to be reused.
