### ISSUE TITLE
Ensure that presentations are available online by default when they are given

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#75]
All too often, meeting presentations at scientific conferences are not shared at all. For Force11 meetings, most presentations are actually made available at some point, but the problem here is the time lag between when the presentation is given and when it is available online.

We should strive to have some online version of the presentations available at the latest when the talk/ demo/ poster etc. is presented, and preferably a few minutes or hours earlier. This makes it much more efficient to actually follow the presentation and to engage with it in terms of posting questions or comments and in terms of sparking collaboration and reaching out into a wider community more quickly.

While archived presentations are being used, sharing them with the original audience in time for the original event seems to be a straightforward way to improve conference experiences.

**Comment by bmkramer** [comment]
This issue was moved to force11/force2018#10
