### ISSUE TITLE
Arrange graphic notetakers

### ISSUE THREAD

**Issue by kamc** [force11/force2017#76]
Note from 2016 - "Graphic notetakers were enjoyed by all"

Do we wish to do that again this year? How would we proceed with that?

**Comment by bmkramer** [comment]
Force has used the services of 'Jongens van de Tekeningen' in both Oxford (right?) and Portland. They're Netherlands-based, so travel costs will be cheaper than for Force2016.

Of course, we can also look for Berlin-based graphic notetakers, both for local flavour, contact with local communities and cost-effectiveness. (and I'm saying that as a huge fan of Jongens van de Tekeningen)

I'd be happy to liaison with Jongens van de Tekeningen if we want to go that route. 
i

**Comment by kamc** [comment]
Yes - I thought they have been a FABULOUS addition the last two years! I would be thrilled to have them there again.

**Comment by Daniel-Mietchen** [comment]
There are some good ones in Germany too - examples in https://commons.wikimedia.org/wiki/Category:Graphic_recording .

**Comment by nicolevasilevsky** [comment]
Yes, Jongens van de Tekeningen' was at Oxford and in Portland, and I agree, they are great. +1 to using them again.

**Comment by kamc** [comment]
Are we doing this? If so, we should likely set it up asap to get on Jongens schedule or find someone else and get on theirs.
