### ISSUE TITLE
Inform speakers that they need to register and pay for conference

### ISSUE THREAD

**Issue by kamc** [force11/force2017#78]
Comment from Force2016 - "We had a lot of really great invited speakers for the sessions, however it wasn’t clear to them that they needed to register and pay for the conference. Session chairs should inform their speakers that they need to register and pay for the conference, OR we should pay for them. There were a lot of assumptions that they would not need to pay." 

This might be VERY important to address before we send out the to make it clear that speakers will be expected to get themselves there and register. Could there be some possibility of inviting them to apply as Fellows?

**Comment by natesjacobs** [comment]
But hopefully not for keynotes, correct?

**Comment by bmkramer** [comment]
Email sent out to all participants about the need to register. Closing for now.
