### ISSUE TITLE
Publicity plan - what is the program committee's role with publicity?

### ISSUE THREAD

**Issue by kamc** [force11/force2017#80]
Comments from Force2016 - 

1. "Need to have a well defined publicity plan at the beginning of the conference planning and a point person to move this forward. Lack of an all-member listserv made it hard to communicate." 

2. "The use of a assigned blogger really helped capture the planning and excitement up until the conference and we got a lot of positive feedback."

What is our role? What do we need to do in helping with publicity or how do we support those efforts of others?

**Comment by nicolevasilevsky** [comment]
We need to coordinate key dates and let us know when you would like us to send out announcements and such.
