### ISSUE TITLE
Venue seating for networking

### ISSUE THREAD

**Issue by kamc** [force11/force2017#83]
From Force2016 - "Need seating in the venue for people who are not in the session. We lost a lot of people to the local cafes instead of them mingling together in the facility. There were some complaints about lack of seating at lunch time."

Relates to a few different issues like #32 and #14 and others.

**Comment by Daniel-Mietchen** [comment]
Perhaps this is less about seating and more about tables, which could be tables at which people are standing.

**Comment by kamc** [comment]
May depend a good bit on what we decide to do during lunches.
