### ISSUE TITLE
Consider doing a doathon

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#84]
This came up in the outreach committee two weeks or so ago and was basically postponed.

Could simply be part of the unconference or fed into some of the satellite events.

**Comment by Daniel-Mietchen** [comment]
Renamed from hackathon to doathon to make it more inclusive.
Some materials for organizing a doathon are being gathered at https://github.com/sparcopen/do-a-doathon , based on the experience with organizing one in March this year:
https://github.com/sparcopen/Open-Research-doathon .

**Comment by terrainsvagues** [comment]
We could also call this a make-a-thon, to play on the idea of maker spaces in libraries, etc.

**Comment by Daniel-Mietchen** [comment]
Suggested theme: citations.
