### ISSUE TITLE
Prepare a Twitter archive

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#87]
not sure what the best option for that is these days, so this is just a quick flag for the moment.

**Comment by nicolevasilevsky** [comment]
we have done this in the past, but I don't know who the point person was for that, maybe it was @sthagstrom? (Personally, I don't know how to do this).

**Comment by Daniel-Mietchen** [comment]
Not sure anyone has done that, so here's a link to a how-to, with an example from #WikidataCon
https://hawksey.info/tagsexplorer/?key=1LpBM-xI9I5pVV-LabNkdy9UQp0lvQhMpSmb5AYdLTuk&gid=400689247&mentions=true .

**Comment by Daniel-Mietchen** [comment]
Oops - the how-to sits at https://mashe.hawksey.info/2011/11/twitter-how-to-archive-event-hashtags-and-visualize-conversation/ .

**Comment by nicolevasilevsky** [comment]
@Daniel-Mietchen have you used this tool before? I am having trouble getting it to work.

**Comment by nicolevasilevsky** [comment]
@sthagstrom do you remember which tool you used in the past to archive the tweets?

**Comment by bmkramer** [comment]
I did (mostly to export the data to make a network viz). I can have a look
over the weekend to see if it still works for me.

2017-11-03 0:46 GMT+01:00 Nicole Vasilevsky <notifications@github.com>:

**Comment by nicolevasilevsky** [comment]
Awesome, thank you @bmkramer!

**Comment by nicolevasilevsky** [comment]
@bmkramer have you had a chance to look at aggregating the Tweets from Force2017? I still can't figure it out.
Thanks!

**Comment by bmkramer** [comment]
@nicolevasilevsky Hm, I can collect recent tweets (e.g. from #chs17) alright - see https://docs.google.com/spreadsheets/d/1tOflyDW1oY6hUA4WlQD7KQ6OSJ44uDchaRUqIo2sr9Y/edit#gid=8743918

However, in the FAQ from Martin Hawksey's TAGS script it says:
(https://tags.hawksey.info/get-tags/)

Q: Why I’m I only getting Twitter search results from the last 6-9 days?
A: This is a limitation of the Twitter service. Twitter says:
The Search API is not complete index of all Tweets, but instead an index of recent Tweets. At the moment that index includes between 6-9 days of Tweets.

:-(

**Comment by Daniel-Mietchen** [comment]
I've just dug around a bit but could not find anything useful. Notes in https://github.com/Daniel-Mietchen/ideas/issues/138 .
