### ISSUE TITLE
Notify outreach committee once the call for proposals is out

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#88]
depends on #57 and #68.

**Comment by bmkramer** [comment]
Submission form is now ready for distribution:

Link to admin view (including responses)
https://docs.google.com/forms/d/1yHOZAVVLaPwzFneDc-DGSO25zssKOnrKpoXkMAzzSxM

Link to viewable form for distribution: 
https://docs.google.com/forms/d/e/1FAIpQLSfYPGFaIzZ6I_TaOGjcr45IUuga2rHvLPXUc6cYbUyywqwhHg/viewform

Short url to viewable form:
https://tinyurl.com/force2017-proposals
and with preview:
http://preview.tinyurl.com/force2017-proposals

I asked Stephanie to coordinate this with Copernicus for inclusion on the website. Once that is done, further dissemination can start. 

Random thought: it might be good to create a short URL for the form. [edited: **done**]

**Comment by mfenner** [comment]
Abstract submissions are open as of July 12: http://www.force2017.org/abstract_submissions/call_for_abstracts.html. Outreach committee (and the other committees) has been informed.
