### ISSUE TITLE
Add publicity materials to website

### ISSUE THREAD

**Issue by nicolevasilevsky** [force11/force2017#94]
Add publicity materials, I mocked up some content here: https://docs.google.com/document/d/1QRnBel0v4Q7VBhz28T3aAJCMTSsA34k5NlNSUAn_tdw/edit# 

Similar to last year: https://www.force11.org/meetings/force2016/force2016-publicity-materials

**Comment by natesjacobs** [comment]
General question here, is Copernicus managing all the web dev stuff?  Or did they just setup the CMS and are giving us admin accounts to manage the content, pages, etc?

**Comment by nicolevasilevsky** [comment]
@mfenner or @sthagstrom should be able to answer this- I think they are meant to be the point of contact with Copernicus, and Copernicus is meant to update/manage the website.
