### ISSUE TITLE
create a list of bullet points about Force2017 that can be used for publicity via various means

### ISSUE THREAD

**Issue by nicolevasilevsky** [force11/force2017#96]
We had something like this last year, and it was shared on the Force2016 website under publicity materials:

https://docs.google.com/document/d/1i6h-8r-y5i0HG8YEFXGbmukFCabCvPtjSVFthNJBMOg/edit

related to #94

**Comment by natesjacobs** [comment]
some of this info is in this doc:
https://docs.google.com/document/d/1IcsCM7R-4_puS6G-5YLY_GP6Hj_aZuc_tAkITZn7_Xk/edit

but there should probably be one specifically tailored for press releases.  I copied the 2016 document and put it in the same folder so we can start editing it:
https://docs.google.com/document/d/1rIXCqBXHhyhFJkrzJeaw1eo2aIQYckQtZI1FIiYk9Rs/edit
