### ISSUE TITLE
create flyer for outreach

### ISSUE THREAD

**Issue by nicolevasilevsky** [force11/force2017#97]
Laura is going to help with this

**Comment by natesjacobs** [comment]
Also would be good if not too much work to create graphics for posting on social media (e.g., image on twitter) which should have less info / text for viewing on mobile devices

**Comment by nicolevasilevsky** [comment]
@natesjacobs we do have some logos for Force2017, can you access this [folder](https://drive.google.com/drive/u/0/folders/0B-3fjDTO3dDaRHU1SFhwVUpsVjg)? If not, can you send me your email for your google account?
