### ISSUE TITLE
Create short URL for submission form

### ISSUE THREAD

**Issue by Daniel-Mietchen** [force11/force2017#99]
as per https://github.com/force11/force2017/issues/88#issuecomment-309396447 , 
ideally customizable to something like
.../force2017-submission

**Comment by bmkramer** [comment]
https://tinyurl.com/force2017-submission

and with preview:
http://preview.tinyurl.com/force2017-submission

**Comment by bmkramer** [comment]
Short url to viewable form:
https://tinyurl.com/force2017-proposals

and with preview:
http://preview.tinyurl.com/force2017-proposals
